// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SanitaOggi.Models;
using System;

namespace SanitaOggi.Migrations
{
    [DbContext(typeof(SanitaContext))]
    [Migration("20171220144144_AddRiferimentiInAmbulatoion")]
    partial class AddRiferimentiInAmbulatoion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SanitaOggi.Models.Ambulatorio", b =>
                {
                    b.Property<string>("AmbulatorioID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodStruttura")
                        .IsRequired();

                    b.Property<string>("CodTipo")
                        .IsRequired();

                    b.Property<int>("StrutturaID");

                    b.Property<string>("StrutturaID1");

                    b.Property<int>("TipoAmbulatorioID");

                    b.Property<string>("TipoAmbulatorioID1");

                    b.HasKey("AmbulatorioID");

                    b.HasIndex("StrutturaID1");

                    b.HasIndex("TipoAmbulatorioID1");

                    b.ToTable("Ambulatorio");
                });

            modelBuilder.Entity("SanitaOggi.Models.Struttura", b =>
                {
                    b.Property<string>("StrutturaID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodiceStruttura")
                        .IsRequired();

                    b.Property<string>("NomeStruttura")
                        .IsRequired();

                    b.HasKey("StrutturaID");

                    b.ToTable("Struttura");
                });

            modelBuilder.Entity("SanitaOggi.Models.TipoAmbulatorio", b =>
                {
                    b.Property<string>("TipoAmbulatorioID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodiceTipo")
                        .IsRequired();

                    b.Property<string>("NomeTipo")
                        .IsRequired();

                    b.HasKey("TipoAmbulatorioID");

                    b.ToTable("TipoAmbulatorio");
                });

            modelBuilder.Entity("SanitaOggi.Models.Ambulatorio", b =>
                {
                    b.HasOne("SanitaOggi.Models.Struttura", "Struttura")
                        .WithMany()
                        .HasForeignKey("StrutturaID1");

                    b.HasOne("SanitaOggi.Models.TipoAmbulatorio", "TipoAmbulatorio")
                        .WithMany()
                        .HasForeignKey("TipoAmbulatorioID1");
                });
#pragma warning restore 612, 618
        }
    }
}
